"""added displayname

Revision ID: 27f05f4074e5
Revises: 60e0e639b229
Create Date: 2019-01-06 20:00:10.575768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f05f4074e5'
down_revision = '60e0e639b229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('displayname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_displayname'), 'user', ['displayname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_displayname'), table_name='user')
    op.drop_column('user', 'displayname')
    # ### end Alembic commands ###
